[package]
name = "luz2d-rs"
version = "0.1.0"
authors = ["vinifreitas.d.a"]
edition = "2018"

[profile.release]
debug = true

[dependencies]
image = "^0.24"
rand = "^0.8"
rayon = "^1.5"
nalgebra = "0.31.1"